### ISSUE TITLE
Not downloading .torrents from custom RSS feed

### ISSUE THREAD

**Issue by patrickrushton** [mipstian/catch#169]
I'm running Catch 2.0 alpha 5 on macOS 10.13.6

I've added an [RSS feed](https://tvchaosuk.com/rss/3002.f41088552cd1bad3cea10933e00e7c11). When I select Check Now from the menu bar app, I get 45 notifications in Notification Center  about the new episodes that have been found.

But that's all that happens. There aren't any .torrent files downloaded and Transmission is not opened. If I select Recent Episodes from the menu bar app, I just see an empty window.

I've tried the same feed url in qBitTorrent and it worked great, but I'd prefer to use Catch and Transmission.

**Comment by mipstian** [comment]
That's because the links in the feed do not end in `.torrent` and therefore the app considers them generic URLs instead of torrent files. Not sure how this could be solved?

**Comment by mipstian** [comment]
This should be fixed in RC1, please let me know if it isn't 😉

**Comment by patrickrushton** [comment]
I just tried again using the feed mentioned in my original post and it's still not downloading anything. Behaviour seems to be unchanged - I get notifications that new episodes have been added, but nothing else happens.

**Comment by mipstian** [comment]
Definitely fixed in RC2 :)
https://github.com/mipstian/catch/releases/tag/2.0-rc2
